apiVersion: v1
kind: Service
metadata:
  name: {{ include "buun-curator.fullname" . }}-agent
  labels:
    {{- include "buun-curator.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "buun-curator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
