{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buun-curator.serviceAccountName" . }}
  labels:
    {{- include "buun-curator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.migration.enabled }}
    # ServiceAccount must be created before migration job (weight: -1)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
