apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buun-curator-external-secret
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/s3
      metadataPolicy: None
      property: access_key
    secretKey: S3_ACCESS_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/s3
      metadataPolicy: None
      property: secret_key
    secretKey: S3_SECRET_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/s3
      metadataPolicy: None
      property: public_url
    secretKey: S3_PUBLIC_URL
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: buun-curator-e2e/deep_l
  #     metadataPolicy: None
  #     property: api_key
  #   secretKey: DEEPL_API_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/microsoft
      metadataPolicy: None
      property: subscription_key
    secretKey: MS_TRANSLATOR_SUBSCRIPTION_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/microsoft
      metadataPolicy: None
      property: region
    secretKey: MS_TRANSLATOR_REGION
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/litellm
      metadataPolicy: None
      property: api_key
    secretKey: OPENAI_API_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/langfuse
      metadataPolicy: None
      property: public_key
    secretKey: LANGFUSE_PUBLIC_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/langfuse
      metadataPolicy: None
      property: secret_key
    secretKey: LANGFUSE_SECRET_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/langfuse
      metadataPolicy: None
      property: host
    secretKey: LANGFUSE_HOST
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: buun-curator-e2e/keycloak
  #     metadataPolicy: None
  #     property: auth_url
  #   secretKey: KEYCLOAK_URL
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: buun-curator-e2e/keycloak
  #     metadataPolicy: None
  #     property: app_url
  #   secretKey: BETTER_AUTH_URL
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: buun-curator-e2e/keycloak
  #     metadataPolicy: None
  #     property: client_id
  #   secretKey: KEYCLOAK_CLIENT_ID
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: buun-curator-e2e/keycloak
  #     metadataPolicy: None
  #     property: client_secret
  #   secretKey: KEYCLOAK_CLIENT_SECRET
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/internal-api
      metadataPolicy: None
      property: api_token
    secretKey: INTERNAL_API_TOKEN
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/better-auth
      metadataPolicy: None
      property: secret
    secretKey: BETTER_AUTH_SECRET
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/github
      metadataPolicy: None
      property: token
    secretKey: GITHUB_TOKEN
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: buun-curator-e2e/meilisearch
      metadataPolicy: None
      property: api_key
    secretKey: MEILISEARCH_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: buun-curator-secret
